-- KIZOMBA ATLAS — AJOUT DES 4 AFFICHES
-- À exécuter dans Supabase > SQL Editor.
-- Le 14 juillet 2026 étant passé, Saïda Kizomba est conservé en brouillon/archives.

insert into public.events (
  id, title_fr, title_en, description_fr, description_en,
  organizer_name, category, styles, map_style,
  starts_at, ends_at, venue_name, address, city, country,
  latitude, longitude, image_url, logo_url, ticket_url,
  price_text_fr, price_text_en, status
)
values
(
  'initiation-kizomba-rochecorbon-2026-07-28',
  'Initiation Kizomba — Guinguette de Rochecorbon',
  'Kizomba Introduction — Guinguette de Rochecorbon',
  'Initiation Kizomba à 19h30, démonstrations, renseignements et inscriptions pour la rentrée danse Kizomba 2026/27.',
  'Kizomba introduction at 7:30 pm, demonstrations, information and registration for the 2026/27 Kizomba season.',
  'Malembé Kizomba Academy',
  'workshop',
  array['kizomba'],
  'kizomba',
  timestamptz '2026-07-28 19:30:00 Europe/Paris',
  null,
  'La Guinguette de Rochecorbon',
  'Quai de la Loire, 37210 Rochecorbon',
  'Rochecorbon',
  'France',
  47.4080,
  0.7582,
  'https://kizomba-atlas.vercel.app/assets/events/guinguette-rochecorbon-28-juillet-2026.png',
  null,
  'https://www.instagram.com/p/DavR6IgoAiR/',
  '',
  '',
  'published'
),
(
  'saida-kizomba-2026-07-14',
  'Saïda Kizomba — 2 salles Kizomba & Konpa',
  'Saïda Kizomba — Kizomba & Konpa in 2 rooms',
  'Événement du mardi 14 juillet 2026 avec une salle Kizomba et une deuxième salle Konpa. Conservé dans les archives car la date est passée.',
  'Tuesday 14 July 2026 event with one Kizomba room and a second Konpa room. Kept in the archive because the date has passed.',
  'Saïda Kizomba',
  'party',
  array['kizomba'],
  'kizomba',
  timestamptz '2026-07-14 20:00:00 Europe/Paris',
  null,
  'Sensation Dance School',
  '105 Rue de Tolbiac, Dalle des Olympiades, 75013 Paris',
  'Paris',
  'France',
  48.82658,
  2.364743,
  'https://kizomba-atlas.vercel.app/assets/events/saida-kizomba-14-juillet-2026.jpg',
  null,
  'https://www.instagram.com/p/DabCasGM9pK/',
  '',
  '',
  'draft'
),
(
  'my-africana-vibes-kizomba-semba-2026-2027',
  'Cours Kizomba & Semba 2026–2027 — My Africana Vibes',
  'Kizomba & Semba Classes 2026–2027 — My Africana Vibes',
  'Cours tous les mardis : 19h45 Kizomba/Semba intermédiaire, 20h45 Kizomba/Semba débutant évolutif. Portes ouvertes les 15 et 22 septembre 2026.',
  'Classes every Tuesday: 7:45 pm intermediate Kizomba/Semba, 8:45 pm progressive beginner Kizomba/Semba. Open days on 15 and 22 September 2026.',
  'My Africana Vibes',
  'workshop',
  array['kizomba','semba'],
  'semba',
  timestamptz '2026-09-15 19:45:00 Europe/Paris',
  timestamptz '2027-06-15 22:00:00 Europe/Paris',
  'Salle Noël Marchand',
  '99 Boulevard Charles de Gaulle, 37540 Saint-Cyr-sur-Loire',
  'Saint-Cyr-sur-Loire',
  'France',
  47.413159,
  0.672493,
  'https://kizomba-atlas.vercel.app/assets/events/my-africana-vibes-2026-2027.png',
  null,
  'https://www.helloasso.com/associations/my-africana-vibes',
  'Inscriptions : voir la page officielle',
  'Registration: see official page',
  'published'
),
(
  'curtis-kelly-tous-les-jeudis-2026-2027',
  'Urban Kiz & Kizomba tous les jeudis — Curtis & Kelly',
  'Urban Kiz & Kizomba Every Thursday — Curtis & Kelly',
  'Tous les jeudis dès la rentrée de septembre 2026, de 20h30 à 2h, avec Curtis & Kelly. En partenariat avec Sensa’Kiz et KIZ.',
  'Every Thursday from September 2026, 8:30 pm to 2:00 am, with Curtis & Kelly. In partnership with Sensa’Kiz and KIZ.',
  'Curtis & Kelly / Sensa’Kiz',
  'party',
  array['urban-kiz','kizomba'],
  'urban-kiz',
  timestamptz '2026-09-03 20:30:00 America/Toronto',
  timestamptz '2027-06-25 02:00:00 America/Toronto',
  'L.E Mango — Espaces des Arts',
  '9 Rue Sainte-Catherine Est, 2e étage, Montréal, QC H2X 1K3',
  'Montréal',
  'Canada',
  45.5103209,
  -73.5637369,
  'https://kizomba-atlas.vercel.app/assets/events/curtis-kelly-jeudis-2026.png',
  null,
  null,
  '',
  '',
  'published'
)
on conflict (id) do update set
  title_fr = excluded.title_fr,
  title_en = excluded.title_en,
  description_fr = excluded.description_fr,
  description_en = excluded.description_en,
  organizer_name = excluded.organizer_name,
  category = excluded.category,
  styles = excluded.styles,
  map_style = excluded.map_style,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  venue_name = excluded.venue_name,
  address = excluded.address,
  city = excluded.city,
  country = excluded.country,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  image_url = excluded.image_url,
  logo_url = excluded.logo_url,
  ticket_url = excluded.ticket_url,
  price_text_fr = excluded.price_text_fr,
  price_text_en = excluded.price_text_en,
  status = excluded.status,
  updated_at = now();
